"""
Session classifier.

Uses Google Gemini to classify sessions based on the behavioral prompt.
"""

import json
import os
from google import genai
from google.genai import types

PROMPT_TEMPLATE = """You are an expert coding integrity analyst. Your job is to examine a candidate's
coding session log from a live technical interview and determine whether the code
was written organically by the candidate, pasted from an external source, or
generated by an AI tool.

You will receive a JSON object representing a single coding session. It contains:
- session_id, problem_id, language, session_duration_seconds
- code: the final code the candidate submitted
- events: a chronological list of behavioral events (keystroke, delete, paste,
  cursor_jump, pause)

Your task is to classify the session into exactly one of these categories:
- "organic": The candidate wrote the code themselves, thinking and typing in
  real time. Organic sessions show natural human variation: inconsistent typing
  speeds, thinking pauses followed by imperfect bursts, deletions and rewrites,
  variable renaming, and iterative refinement. The code may have rough edges.
- "pasted": The candidate pasted code from an external source (e.g., copied from
  a browser, notes, or another file). Pasted sessions are dominated by paste
  events that contain large blocks of code. There are few or no corrections after
  pasting. The keystroke-to-total-code ratio is very low. The session is often
  suspiciously short relative to the problem complexity.
- "ai_generated": The code was produced by an AI tool (e.g., Copilot, ChatGPT).
  AI-generated sessions may appear as keystrokes (auto-inserted by the tool), but
  the behavioral fingerprint is distinctive: typing speed is unnaturally uniform
  (very low variance in avg_ms_between_keys across bursts), there are almost zero
  deletions or corrections, the code is excessively polished (comprehensive
  docstrings, type hints, multiple implementations, thorough edge-case tests),
  and the output volume is disproportionately high relative to session duration.

--- ANALYSIS FRAMEWORK ---

Analyze the session by working through these five steps IN ORDER. For each step,
note what you observe before reaching a conclusion.

STEP 1: Typing Rhythm Analysis
- Calculate the range and variance of avg_ms_between_keys across all keystroke
  events.
- Organic typing shows HIGH variance (e.g., 110-290ms range). Humans speed up on
  familiar code and slow down on tricky parts.
- AI-generated typing shows LOW variance (e.g., 95-112ms range). The uniformity
  is the strongest single signal for AI generation.
- Very fast uniform typing (< 80ms average) with no pauses suggests automated
  insertion.

STEP 2: Deletion and Correction Patterns
- Count the number of delete events and total chars_deleted.
- Calculate the deletion ratio: total_chars_deleted / total_chars_typed.
- Organic sessions have a meaningful deletion ratio (typically 5-20%). Humans
  make mistakes, change variable names, restructure code, try one approach and
  switch to another.
- AI-generated sessions have near-zero deletions. The code comes out clean.
- Pasted sessions have near-zero deletions after the paste event specifically.
  Any deletions tend to happen before or unrelated to the main code.

STEP 3: Paste Event Analysis
- Count the number of paste events and their content_length values.
- If paste events deliver the majority of the final code (paste_chars /
  total_code_length > 0.5), this strongly suggests "pasted".
- A single large paste (>100 chars) containing functional code (not just
  boilerplate/imports/comments) with minimal follow-up corrections = strong
  "pasted" signal.
- Small pastes of boilerplate (JSDoc comments, import statements) are normal
  in organic sessions and should NOT trigger a "pasted" classification.

STEP 4: Temporal Flow and Session Pacing
- Examine the distribution of pauses. Organic sessions have pauses of varying
  lengths at natural thinking points (before starting a new function, before
  writing a tricky condition, before refactoring).
- Look for the "AI wait" pattern: a long pause (30-60+ seconds) followed by a
  sudden burst of clean, fast code with no corrections. One such instance might
  be normal thinking; a repeated pattern of pause-then-perfect-burst suggests
  AI generation.
- Very short total session duration relative to code complexity and length
  suggests pasting or AI generation, not organic work.
- Look at cursor_jump events: jumping back to refactor earlier code is a strong
  organic signal. Cursor jumps only to navigate after pasting = not organic.

STEP 5: Code Quality vs. Behavioral Effort
- Compare the polish level of the final code against the behavioral evidence of
  effort.
- Organic code often has informal variable names, minimal or no docstrings, and
  simple tests. The code "shows its work."
- AI-generated code tends to be disproportionately polished: full Google/NumPy
  style docstrings, type hints throughout, multiple solution approaches, edge
  case handling, and comprehensive test suites - all produced with suspiciously
  little effort or correction.
- If the code looks like it came from a textbook but the event log shows no
  struggle, be suspicious.

--- OUTPUT FORMAT ---

Respond with ONLY a JSON object in this exact format, no other text:

{
  "classification": "organic" | "pasted" | "ai_generated",
  "confidence": "low" | "medium" | "high",
  "reason": "<one sentence explaining the primary evidence for your classification>"
}

Rules for confidence levels:
- "high": Multiple strong signals all point to the same classification with no
  contradictory evidence.
- "medium": The primary signals point to one classification, but there is some
  ambiguity or one contradictory signal.
- "low": The signals are mixed or borderline. You are making a judgment call.

IMPORTANT: When in doubt, lean toward "organic". Falsely accusing an honest
candidate of cheating is far more damaging than missing a cheater. If a session
could plausibly be either organic or suspicious, classify it as organic with
low confidence.

--- SESSION DATA ---

"""

client = genai.Client(api_key=os.environ.get("GOOGLE_API_KEY"))

def classify_session(session: dict) -> dict:
    """
    Classify a coding session as organic / pasted / ai_generated.
    """
    session_json = json.dumps(session, indent=2)
    full_prompt = PROMPT_TEMPLATE + session_json

    response = client.models.generate_content(
        model='gemini-2.5-flash',
        contents=full_prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            temperature=0.1
        )
    )

    try:
        result = json.loads(response.text)
        return {
            "session_id": session["session_id"],
            "label": result.get("classification", "unknown"),
            "confidence": result.get("confidence", "unknown"),
            "reason": result.get("reason", "No reason provided")
        }
    except Exception as e:
        return {
            "session_id": session["session_id"],
            "label": "error",
            "confidence": "low",
            "reason": f"Failed to parse JSON: {e}"
        }
